CountMeIn/Models/LeagueViewModels/LeagueViewModel.cs
using CountMeIn.AppModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CountMeIn.Models.LeagueViewModels
{
    public class LeagueViewModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }

        public List<CountMeInUser> Players { get; set; }
        public List<CountMeInUser> Organizers { get; set; }
        public List<Meetup> Meetups { get; set; }
    }
}

CountMeIn/Controllers/LeagueController.cs
using System;
using System.Threading.Tasks;
using CountMeIn.AppModels;
using CountMeIn.Data.DataModels;
using CountMeIn.Models;
using CountMeIn.Models.LeagueViewModels;
using CountMeIn.Repositories;
using CountMeIn.Repositories.Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CountMeIn.Controllers
{
    public class LeagueController : Controller
    {
        LeagueRepository repo;
        private readonly UserManager<CountMeInUser> _userManager;

        public LeagueController(
            ILeagueRepository leagueRepo,
            UserManager<CountMeInUser> userManager)
        {
            repo = (LeagueRepository)leagueRepo;
        }


        // GET: /<controller>/
        public IActionResult Index(Guid LeagueId)
        {            
            var league = (repo.GetById(LeagueId)).Result;
            var model = new LeagueViewModel()
            {
                Id = league.Id,
                Name = league.Data.Name,
                Meetups = league.Data?.Meetups,
                Organizers = league.Data?.Organizers,
                Players = league.Data?.Players
            };

            return View(model);
        }


        [HttpGet]
        public IActionResult Create()
        {
            var model = new CreateLeagueViewModel();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateLeagueViewModel model)
        {
            if (ModelState.IsValid)
            {
                var appModel = new League
                {
                    Name = model.Name,
                    Id = Guid.NewGuid()                    
                };

                var user = await _userManager.GetUserAsync(User);
                appModel.Organizers.Add(user);
                appModel.Players.Add(user);

                await repo.Add(new LeagueModel { Id = appModel.Id, Data = appModel});

                return RedirectToAction("Index", "League", appModel.Id);
            }
            return View(model);
        }
    }
}

CountMeIn/Controllers/MeetupController.cs
using System;
using System.Threading.Tasks;
using CountMeIn.AppModels;
using CountMeIn.Data.DataModels;
using CountMeIn.Models.MeetupViewModels;
using CountMeIn.Repositories;
using CountMeIn.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CountMeIn.Controllers
{
    public class MeetupController : Controller
    {
        MeetupRepository repo;
        LeagueRepository leagueRepo;

        public MeetupController(IMeetupRepository repo, ILeagueRepository leagueRepo)
        {
            this.repo = (MeetupRepository)repo;
            this.leagueRepo = (LeagueRepository)leagueRepo;
        }


        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create(Guid leagueId)
        {
            var model = new CreateMeetupViewModel();
            model.LeagueId = leagueId;
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateMeetupViewModel model)
        {
            if (ModelState.IsValid)
            {
                var appModel = new Meetup
                {
                    Id = Guid.NewGuid(),
                    Time = model.Time,
                    Location = model.Location,
                    Description = model.Description
                };
                var league = (leagueRepo.GetById(model.LeagueId)).Result;
                appModel.League = league.Data;

                await repo.Add(new MeetupModel { Id = appModel.Id, Data = appModel });
            }

            return View(model);
        }
    }
}

CountMeIn/Views/League/Create.cshtml
@model CreateLeagueViewModel

@{
    ViewData["Title"] = "Register Your League";
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="col-md-4">
        <form asp-route-returnUrl="@ViewData["ReturnUrl"]" method="post">
            <h4>Create a new League.</h4>
            <hr />
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name">Register your league</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>            
            <button type="submit" class="btn btn-default">Register</button>
        </form>
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

CountMeIn/Views/League/Index.cshtml
@model LeagueViewModel

@{
    ViewData["Title"] = Model.Name;
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="col-lg-10">
        Create a Matchday for <b>@Model.Name</b>
        <a class="btn btn-default" href=@Url.Action("Create", "Meetup", Model.Id)>
            Create Match Day
        </a>
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}